let salarioAnual;(x / x)
{
let resultado = (x / x)
return resultado
} 

console.log (calcular,salarioAnual (x/x))


//Practica2
let salarioMensual;(x*x)
{
  let resultado =(x*x)
   return resultado
} console.log(calcular,salarioMensual(x*x))



//Practica3
let promedio;(Nota1,Nota2,Nota3)
{
    alert(Nota1,Nota2,Nota3)
    prompt(4,5,6)
}






















